---
- hosts: bread
  become: true

  # vars:
  #   script_name: /home/pi/install-pihole.sh

  tasks:
    - include_tasks: tasks/common.yml

    - name: Enable I2C
      command: "raspi-config nonint do_i2c 0"

    - name: Enable SPI
      command: "raspi-config nonint do_spi 0"

    # add an apt upgrade to this stanza (also check python-dev):
    # sqlite3 libv4l-dev imagemagick? subversion?
    # linux-headers-rpi python-dev build-essential
    # linux-kernel-headers / linux-libc-dev
    # libjpeg8-dev / libjpeg62-turbo-dev
    # v4l-utils fswebcam
    # "python-rpi.gpio" (auto-installed?)
    - name: Install python3 dev packages
      apt:
        name:
          - python3-pip
          - python3-django
          - sqlite3
          - python3-rpi.gpio
          - rrdtool
          - librrd-dev
          - tio
        state: latest

    - name: Install PIP packages
      pip:
        name:
        - rrdtool
        - rshell
        - mpremote
        - adafruit-ampy
        state: present
        executable: "pip3"

# maybe also:
#        - "i2c-tools"
