---
- hosts: raspberrypi
  become: true

  vars:
    wifi_country: "US"
    rpi_timezone: "US/Pacific"
    #rpi_keyboard: "pc105"
    rpi_keyboard_layout: "us"
    rpi_locale: "en_US"

  vars_prompt:
    - name: rpi_hostname
      prompt: "enter hostname for new device:"
      private: no
    - name: rpi_password
      prompt: "enter new password for pi user:"
      #private: yes
      private: no
    - name: wifi_ssid
      prompt: "please enter the WiFi SSID for your new device:"
      private: no
    - name: wifi_password
      prompt: "please enter the WiFi password for your new device:"
      #private: yes
      private: no

  roles:
    - piconfig

  tasks:
    - debug:
        msg="Done - rerun with playbook for {{ rpi_hostname }}"

# reboot


