---
- hosts: kali
  become: true

  tasks:
    - include_tasks: tasks/common.yml

    - name: Install extra packages for custom network-monitoring
      apt:
        name="{{apt_pkgs}}" state=latest update_cache=yes autoremove=yes
      vars:
       apt_pkgs:
       - tcsh
       - tcpdump
       - ssldump
       - tshark
       - traceroute
       - docker.io
      # This is only in Kali Linux, not in Raspbian:
      # - kismet

    # - name: Configure rsyslog.conf
    #   blockinfile:
    #     path: /etc/rsyslog.conf
    #     backup: yes
    #     insertafter: "#input(type="imtcp""
    #     block: |
    #       # provides UDP syslog reception
    #       module(load="imudp")
    #       input(type="imudp" port="514")
    #
    #       # provides TCP syslog reception
    #       module(load="imtcp")
    #       input(type="imtcp" port="514")

    # # (docker hub login??)
    # - name: Pull default Docker images
    #   community.docker.docker_image:
    #     name: "{{docker_images}}"
    #     source: pull
    #   vars:
    #     docker_host: tcp://kali.bogus.domain:2376
    #     docker_images:
    #     - manios/nagios
    #     - python
    #     - nginx
    #     - portainer/portainer-ce

    # - name: Create default containers
    #   community.docker.docker_container:
    #   name: "{{ default_container_name }}{{ item }}"
    #   image: "{{ default_container_image }}"
    #   command: "{{ default_container_command }}"
    #   state: present
    #   with_sequence: count={{ container_count }}

    - name: Nagios config files
      debug:
        msg: "copy over object files here..."
