---
- hosts: hole
  become: true

  vars:
    script_name: /home/pi/install-pihole.sh

  tasks:
    - include: tasks/common.yml

    - name: Retrieve Pi-Hole install script
      get_url:
        url: https://install.pi-hole.net/
        dest: {{ script_name }}
        mode: 0755

    - name: Running Pi-Hole install script
      command: bash {{ script_name }}
