---
- hosts:
    - hole
    - furmedia
    - kali
    - proof
    - bread
    # volumio?

  become: true

  tasks:
    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade=full
        update_cache=yes
        autoremove=yes

    - name: Check if a reboot is required
      register: f
      ansible.builtin.stat:
        path=/var/run/reboot-required
        get_checksum=no
        get_attributes=no

    - name: Reboot the server
      ansible.builtin.command: /sbin/reboot
      #ansible.builtin.debug:  msg="...would reboot here..."
      when: f.stat.exists is defined and f.stat.exists

    - name: Upgrade pihole SW
      ansible.builtin.command: /usr/local/bin/pihole -up
      when: inventory_hostname == "hole"
